name: tag-test
on:
    check_run:
      types: [rerequested, completed]
jobs:

  basic-ubuntu-20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/tag@v4.27.0
        with:
          tag: "Version1.4"
          url: ${{ secrets.LIQUIBASE_DB_URL }}

