name: tag-test
on:
  push:
    branches:
      - 'main'
jobs:

  basic-ubuntu-20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/tag@v4.27.0
        with:
          tag: "Version1.2"
          changelogFile: ${{ secrets.LIQUIBASE_CHANGELOG_FILE }}
          url: ${{ secrets.LIQUIBASE_DB_URL }}
          username: ${{ secrets.LIQUIBASE_DB_USERNAME }}
          password: ${{ secrets.LIQUIBASE_DB_PASS }}
          logLevel: INFO
