name: update-test
on: push
jobs:

  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/update@v4.27.0
        with:
          changelogFile: ${{ secrets.LIQUIBASE_CHANGELOG_FILE }}
          url: ${{ secrets.LIQUIBASE_DB_URL }}
          username: ${{ secrets.LIQUIBASE_DB_USERNAME }}
          password: ${{ secrets.LIQUIBASE_DB_PASS }}
          logLevel: INFO
